

# CINCLUDES	+= -I../../finn-hlslib/
CINCLUDES 	+= -I C:/Xilinx/Vivado/2018.3/include
# CINCLUDES 	+= -std=c++0x -Wall -Wno-unknown-pragmas -Wall -Wno-unknown-pragmas -Wno-unused-variable -g
CXX			= g++
LDFLAGS		= -lpthread


test: 
	$(CXX) $(CFLAGS) $(CINCLUDES) ultranet.cpp -o test $(LDFLAGS)